# Generated by Django 3.0.2 on 2021-06-03 14:36

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchefUser',
            fields=[
                ('user_main_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dec_num', models.IntegerField()),
                ('dec_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(1900)])),
                ('dec_date', models.DateField(default=datetime.date.today)),
                ('related_part', models.CharField(default='nozom', max_length=64)),
                ('decision_file', models.FileField(null=True, upload_to='%Y/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archef.ArchefUser')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Shab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('markaz', models.PositiveIntegerField()),
                ('mosalsal', models.PositiveIntegerField()),
                ('nat_id', models.PositiveIntegerField(null=True)),
                ('name', models.CharField(max_length=264, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DecisionRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(1900)])),
                ('markaz', models.IntegerField()),
                ('mosalsal', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('national_num', models.IntegerField(validators=[django.core.validators.MaxValueValidator(40000000000000), django.core.validators.MinValueValidator(20000000000000)])),
                ('change_type', models.CharField(max_length=128)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archef.Decision')),
            ],
        ),
        migrations.AddField(
            model_name='archefuser',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archef.Part'),
        ),
        migrations.AddField(
            model_name='archefuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
