# Generated by Django 3.1 on 2020-09-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archef', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='decision_file',
            field=models.FileField(upload_to='files/%Y/'),
        ),
    ]
