# Generated by Django 3.0.2 on 2020-09-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archef', '0002_shab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shab',
            name='name',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='shab',
            name='nat_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
