# Generated by Django 3.0.2 on 2020-09-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archef', '0002_auto_20200909_2310'),
        ('archef', '0003_auto_20200913_1923'),
    ]

    operations = [
    ]
