# Generated by Django 3.0.2 on 2020-09-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archef', '0004_merge_20200918_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='decision_file',
            field=models.FileField(null=True, upload_to='%Y/'),
        ),
    ]
